# Generated by Django 4.0.4 on 2022-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='lg_badge_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='sm_badge_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
