# Generated by Django 4.0.4 on 2022-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_github_link_projects_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='overview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
