# Generated by Django 4.0.4 on 2022-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0002_alter_techstack_lg_badge_url_and_more'),
        ('projects', '0005_projects_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='technology',
        ),
        migrations.AddField(
            model_name='projects',
            name='technology',
            field=models.ManyToManyField(to='techstack.techstack'),
        ),
    ]
